apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-sever
spec:
  project: default
  source:
    repoURL: https://github.com/anhdle14/thee.git
    targetRevision: HEAD
    path: deployment/code-server
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    automated:
      prune: true
