apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/anhdle14/thee.git
    targetRevision: HEAD
    path: deployment/httpbin
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
