apiVersion: v1
kind: Service
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9402
      protocol: TCP
      targetPort: 9402
