apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tekton-pipelines
spec:
  hosts:
    - tekton.int.anhdle14.me
  gateways:
    - istio-system/gateway
  http:
    - route:
        - destination:
            port:
              number: 9097
            host: tekton-dashboard
