apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
spec:
  project: default
  source:
    repoURL: https://github.com/anhdle14/thee.git
    targetRevision: HEAD
    path: deployment/bookinfo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
