apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://docs.projectcalico.org/manifests/calico.yaml

patchesJson6902:
  - path: patches/calico.ds.json
    target:
      kind: DaemonSet
      name: calico-node
