apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Naming thing is hard even for Argoproj Team, they should fix it to everything argo-cd.
namespace: tekton-pipelines

resources:
  - base/dashboard
  - base/pipelines
  - base/tekton-pipelines.vs.yaml

patchesStrategicMerge:
  - patches/tekton-pipelines.ns.yaml
