apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.18.0
    helm:
      releaseName: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  ignoreDifferences: []
  syncPolicy:
    automated:
      prune: true
