apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - base/jaeger.ns.yaml
  - https://github.com/jaegertracing/jaeger-operator/releases/download/v1.32.0/jaeger-operator.yaml

patchesJson6902:
  - path: patches/jaeger.deploy.json
    target:
      version: v1
      group: apps
      kind: Deployment
      name: jaeger-operator
  - path: patches/sa.crb.json
    target:
      version: v1
      group: rbac.authorization.k8s
      kind: ClusterRoleBindings
      name: jaeger-operator
