apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-dex-secret
  namespace: argo-cd
spec:
  encryptedData:
    dex.github.clientID: AgBYzytlFDhaqhwUX2oo77rzAXXdzkRGlrBmwDYYQq0oetF4sLT+BayfsbtG22DtidkE/KHm4Jb/ZOS5uZ8/3gMwwMToTz2GIhvVJXDUySC6myHjGOKIQSLbQLbNqQfXCN8kOy3eOvcMnRoZhsnsmB7EPJDvZRm5AM2CefRu+ly2jEKnt+CFrjV1W0bKBlYbIqyjt7bMhVDn85z/skD+fsQ78xykqzdiDlmbsuYBu490C3unTxQsNFci9A3iI6hQ0a0t76V0lOekXt072Wy1dpgLNSXfa5v63qwx2/vBeAKriu/vuJ9yX1UmiM9GTOwMq5GXUkGAue+I2thh9xt2me47KkBq5RL6syt3hgwqZQGN5xkSQ7tmdAHEHlGS3gNRqUH8sedyNL+hI4aw5zg9EfJrQ1EcIpo3y0HHeYT/1mERHovcC8NFNJxuBiiDj/CjPitncJnz8X2ErRO4QaClH99wuQLkOFpRu39hz/Pmc0jUHDGwfRXGwBWiFRZQa4xFizNJ7mByx7Wld0eQcpgZAIRBknWyrueluAjcNGb/cZY92chq9tjlZp35BWqTDpWD7AXvfP3ISCiD+puhlho8vt1TKpmrZ+XaD1DcItnij4TA76AWHCT/CSzk0JcPbpo3CdKZ/nWI5AfJB/uUEN4dCEKNt7K7Ruqf6MJHrD2Ghiu8OCu5rvVu8em9iLfSo7QOc0KNDCgSJnGrE31Men3GP4EsmpJ+pg==
    dex.github.clientSecret: AgAJWvpUBwRGFKWntG+GGY0snFZXeE2bSr7D0PNtatfN/2Z3vqPMCJJbddIw1QtWxyoPRuOFLEe3YEp2vj/spCWTBaV4OyWaKdmVHECW8eR8/qZPkGM8Ci2ErRsqAnyG6Nbm34dReKEFp+j0BlhVZ4j9VrKYUCXDnnspa/0jaeeqE31lPVhh+8FCuPZZ4Gg4I4HvpAKND8ZWAYcz+PIPwIFzmHTdS4YjS9G8CL8Epxq25oxnfQTRMpa15AD2sdWDL/brHYxE/YBo0LMlFwku6nRDKf64JuYJW3ZI/ejHM6ey6XAkSaH41gAxIpeR0wtXeYUyGH+jQUuGkNFnwM7B5Y7/BIWspjzhOMgIfhMPxCEirT3LgEfG7BNNn0lgnm1W7ElxFW3+EkA3oPlKzwq1z3iXVI8oICC/VClfiLf5/weLw8ey2Ta6CXLz7JrYE5ysTHCN0m9oQIg9NhJaqxJr0/EConEK+qSetqxrIck2ryX6GSwYBwrglnDd9d4LRUK+I4k2C2OJFvbrPf7n5mYUXSTXFHGsv6/0gANYLK9gnyw8Lek+Q6PsPcBcxGFEXB37KYQ6bNIpda8laVLU7mhEb5iNy1RpfwB22qhUtkAbXwjbDoCb5dWuqMFMJQOFjTcP6nOolWpXnYMtmT39hrnQ518gLFjfBKV+kE1VEmDl7GCsiJmbfwjjBwSMiXWfKpWYdrmcj8s0Q8VRfAYF8WXF3a/K/5wplBnbB2V1VhNhmfB5L3aBWgO5xeZ0
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: argo-cd
        app.kubernetes.io/name: argocd-dex-secret
        app.kubernetes.io/part-of: argocd
        argocd.argoproj.io/instance: argo-cd
      name: argocd-dex-secret
      namespace: argo-cd
    type: Opaque

