apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-dex-secret
  namespace: argo-cd
spec:
  encryptedData:
    dex.github.clientID: AgCaBp3Eg2NFqoCDn/8cH6+DUWTAykmI0L+miDFwLBTdUIzhIYoRc/BxYNCYgZG3wthYk70kZGEh8hStwKfM6bHR3S4eKdLi/ChtXiZc7Ndr8Qw0gnESAhPbLaN/TDRJiQ+4eonGT87HE0IAvI8EZS27wr9rYft2ekOWL1v9HipU5cugBMrbGVXt3Nt5J/4WNoubdu8ERFVTCGD/WUMownd8tQPaR9G8GwpXFI/8RM2UOa/HJdKqoBMIbZjkoSMFm7MN9aROz9e7+N0dTVQoDbjruFm3qM9GXtn3NmXVUM0oXMgSQyfhHTSKn8AHtvpGesUouHQea2xZUxP7KwdJExgC7rVpfosUjb8H1Cj9BK9rSx9UkRHb1QhMhsPgfQ4z22CyLTUKVFKIYvy5AAr1eujeLU7EDR4MLjF+7iCjg1zYZ3cYtb6LzpLpf81ktZvtTv2WQqD13sHSK2Kns2jxDHvBCBy0q4mpzOaE5/34S8qH6bfc6cTVbcHwtYFLppmAgZ24tKLQzs9PFQkUaKaM27QuHFvyGyR15r10PqbBxrTWp4F8XNhvKbL4waCHSylyW5bAWgXr0jKlhg3Mo1zN5mveUagTy0+nUMYUFoN8cXZnfk5IJ3MtTQ248FzERqVOzP42HyTBvZ0yrzbVg1zVb4yzq8oQP8z5VhxoQq0UO9IOzpJ7MXT3qeo+1wIMVHDomySU/AwuDOeMWb9ekd8Vnoik7bKNEg==
    dex.github.clientSecret: AgBfzdTPcD8n2qfyBS/FXu+IjRmvsbagRVuVoTZ9Mq4vtIrVaVp5sYEj0WWfe4fr1L1bVWJy3vCa2n3cSAVDLFx4kHIOgS7FlsObU5CKUBpZp0XClonJaQmymeKtJ9Dn8ZWsEnWNONOXnJMbWjA+2IClAgNNl7sJNYIPpC7wNYxHoTB+bkFNNpXKLNZ6chK8IHFX5mB23wxON47yYpl+x/kywHhBVhmG1xKoTzMXAf6L08J/RJTY8/WM/EVmhn7wbf867KOTo+ocnuFbuDlm+9zXh5nJjMkbvPaH0OV2PAuNhhvgIX48vEmK7fxfvIQx5KpBKLVBrgqOLjx/E/LcIRwAUvsVtN1DTVn+UQyc7+m21j06lmLt0xFNsG0DnC94JN6eBrcfafFql+4DDuNZMWbZucuzquOTTbEMJQVUbQayal02hucgBmR3wG8CEGFoFxwB66xTWSsb/rLUNiEgx7jTTklH5YYoQNMeohkPbj/LM7qtCj8s3WSlyICOeecgop6/mBC9c9LbnGqX1gRzC1tUldjSObIGhnjgup2JuZwybbN1NhZdjFfNrhK48ZdN1HSZHX4tF2tCXlgYRUzoFjpLUmELWu07AOQBqe9hwJLBL/DxS8KjR4PlTifMwW308HezC6Gq2DzZ2OQMIJVQZE1Ud1b9LEbuC/M5OOy+CMQ1/RZWmsGC8URLTJyQHmzTCIj+H1f3KOalKKoXRveBaTlQQ0NDUNAKvP3/rVpVE9fEVcbmpeCcpCkx
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: argo-cd
        app.kubernetes.io/name: argocd-dex-secret
        app.kubernetes.io/part-of: argocd
        argocd.argoproj.io/instance: argo-cd
      name: argocd-dex-secret
      namespace: argo-cd
    type: Opaque

