apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-rollouts

resources:
  - base/argo-rollouts.ns.yaml
  - https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
  - https://github.com/argoproj/argo-rollouts/releases/latest/download/dashboard-install.yaml
  - base/argo-rollouts.vs.yaml

patchesStrategicMerge:
  - patches/argo-rollouts-dashboard.svc.yaml
  - patches/argo-rollouts-metrics.svc.yaml
