apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines
spec:
  project: default
  source:
    repoURL: https://github.com/anhdle14/thee.git
    targetRevision: HEAD
    path: deployment/tekton-pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
